use std::{
    env, fs,
    path::{Path, PathBuf},
    process::{Child, Command},
};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let workspace = manifest_dir.parent().unwrap();
    let public_dir = manifest_dir.join("public");

    // emit rerun-if-changed for all fixture files
    let fixtures_dir = manifest_dir.join("fixtures");
    emit_rerun_for_tree(&fixtures_dir);

    fs::create_dir_all(&public_dir).unwrap_or_else(|e| panic!("failed to create public dir: {e}"));

    let wave1_wcs = [
        ("omni-rt/crates/omni-dock", "omni-dock.js", None),
        ("omni-rt/crates/omni-popper", "omni-popper.js", None),
        ("omni-rt/crates/omni-monaco", "omni-monaco.js", None),
        ("omni-rt/crates/omni-mdx", "omni-mdx.js", None),
        (
            "omni-rt/crates/omni-pdfjs",
            "omni-pdfjs.js",
            Some("omni-pdfjs.worker.js"),
        ),
        ("omni-rt/crates/omni-plyr", "omni-plyr.js", None),
        ("omni-rt/crates/omni-pretext", "omni-pretext.js", None),
        ("omni-rt/crates/omni-zenfs", "omni-zenfs.js", None),
    ];
    let wave2_sw = (
        "omni-rt/crates/omni-sw",
        "omni-sw.js",
        Some("omni-sw-register.js"),
    );

    for (crate_rel, _, _) in wave1_wcs.iter().chain(std::iter::once(&wave2_sw)) {
        let crate_dir = workspace.join(crate_rel);
        let src_dir = crate_dir.join("src");
        emit_rerun_for_tree(&src_dir);
        emit_rerun_if_exists(&crate_dir.join("package.json"));
        emit_rerun_if_exists(&crate_dir.join("tsconfig.json"));
        emit_rerun_if_exists(&crate_dir.join("build.ts"));
    }

    build_bashkit_wasm_artifacts(workspace, &workspace.join(wave2_sw.0));

    let mut wave1_children: Vec<(&str, Child)> = Vec::new();
    for (crate_rel, js_name, extra_file) in &wave1_wcs {
        let crate_dir = workspace.join(crate_rel);
        if crate_needs_rebuild(&crate_dir, js_name, *extra_file, &public_dir) {
            let child = spawn_npm_build(&crate_dir, crate_rel);
            wave1_children.push((crate_rel, child));
        }
    }

    for (crate_rel, child) in &mut wave1_children {
        let status = child
            .wait()
            .unwrap_or_else(|e| panic!("failed to wait for npm build in {crate_rel}: {e}"));
        assert!(status.success(), "npm run build failed in {crate_rel}");
    }

    let sw_dir = workspace.join(wave2_sw.0);
    if crate_needs_rebuild(&sw_dir, wave2_sw.1, wave2_sw.2, &public_dir) {
        let sw_status = Command::new("npm")
            .args(["run", "build"])
            .current_dir(&sw_dir)
            .status()
            .unwrap_or_else(|e| panic!("failed to run npm in {}: {e}", wave2_sw.0));
        assert!(
            sw_status.success(),
            "npm run build failed in {}",
            wave2_sw.0
        );
    }

    for (crate_rel, js_name, extra_file) in wave1_wcs.iter().chain(std::iter::once(&wave2_sw)) {
        let crate_dir = workspace.join(crate_rel);

        copy_if_stale(
            &crate_dir.join("dist").join(js_name),
            &public_dir.join(js_name),
        )
        .unwrap_or_else(|e| panic!("failed to copy {js_name}: {e}"));

        if *js_name == "omni-zenfs.js" {
            let wasm_dir = public_dir.join("wasm");
            fs::create_dir_all(&wasm_dir)
                .unwrap_or_else(|e| panic!("failed to create wasm dir: {e}"));
            fs::write(
                wasm_dir.join("omni-zenfs.js"),
                "export * from \"../omni-zenfs.js\";\n",
            )
            .unwrap_or_else(|e| panic!("failed to write wasm/omni-zenfs.js: {e}"));
        }

        if let Some(extra) = *extra_file {
            copy_if_stale(&crate_dir.join("dist").join(extra), &public_dir.join(extra))
                .unwrap_or_else(|e| panic!("failed to copy {extra}: {e}"));
        }

        // copy sql-wasm.wasm for omni-sw
        let wasm_src = crate_dir.join("dist").join("sql-wasm.wasm");
        if wasm_src.exists() {
            copy_if_stale(&wasm_src, &public_dir.join("sql-wasm.wasm"))
                .unwrap_or_else(|e| panic!("failed to copy sql-wasm.wasm: {e}"));
        }

        // copy omni-bashkit runtime artifacts generated by omni-sw build
        for file in [
            "omni-bashkit.js",
            "omni-bashkit_bg.wasm",
            "omni-bashkit_bg.wasm.d.ts",
        ] {
            let src = crate_dir.join("dist").join(file);
            if src.exists() {
                copy_if_stale(&src, &public_dir.join(file))
                    .unwrap_or_else(|e| panic!("failed to copy {file}: {e}"));
            }
        }

        // copy wasm-bindgen snippets required by omni-bashkit.js imports
        let snippets_src = crate_dir.join("dist").join("snippets");
        if snippets_src.exists() {
            let snippets_dst = public_dir.join("snippets");
            copy_dir_recursive_if_stale(&snippets_src, &snippets_dst)
                .unwrap_or_else(|e| panic!("failed to copy snippets dir: {e}"));

            normalize_zenfs_snippet_import(&public_dir)
                .unwrap_or_else(|e| panic!("failed to normalize zenfs snippet import: {e}"));
        }
    }
}

fn emit_rerun_if_exists(path: &Path) {
    if path.exists() {
        println!("cargo:rerun-if-changed={}", path.display());
    }
}

fn emit_rerun_for_tree(path: &Path) {
    if !path.exists() {
        return;
    }

    if path.is_file() {
        println!("cargo:rerun-if-changed={}", path.display());
        return;
    }

    let entries = fs::read_dir(path)
        .unwrap_or_else(|e| panic!("failed to read directory {}: {e}", path.display()));
    for entry in entries {
        let entry =
            entry.unwrap_or_else(|e| panic!("failed to read entry in {}: {e}", path.display()));
        emit_rerun_for_tree(&entry.path());
    }
}

fn crate_needs_rebuild(
    crate_dir: &Path,
    js_name: &str,
    extra_file: Option<&str>,
    public_dir: &Path,
) -> bool {
    let out = public_dir.join(js_name);
    if !out.exists() {
        return true;
    }
    if let Some(extra) = extra_file {
        if !public_dir.join(extra).exists() {
            return true;
        }
    }
    tree_newer_than(&crate_dir.join("src"), &out)
        || file_newer_than(&crate_dir.join("package.json"), &out)
        || file_newer_than(&crate_dir.join("tsconfig.json"), &out)
        || file_newer_than(&crate_dir.join("build.ts"), &out)
        || file_newer_than(&crate_dir.join("build.mjs"), &out)
}

fn spawn_npm_build(crate_dir: &Path, crate_rel: &str) -> Child {
    Command::new("npm")
        .args(["run", "build"])
        .current_dir(crate_dir)
        .spawn()
        .unwrap_or_else(|e| panic!("failed to spawn npm in {crate_rel}: {e}"))
}

fn build_bashkit_wasm_artifacts(workspace: &Path, sw_crate_dir: &Path) {
    let bashkit_src = workspace.join("omni-rt/crates/omni-bashkit/src");
    let bashkit_manifest = workspace.join("omni-rt/crates/omni-bashkit/Cargo.toml");
    emit_rerun_for_tree(&bashkit_src);
    emit_rerun_if_exists(&bashkit_manifest);

    let sw_dist = sw_crate_dir.join("dist");
    fs::create_dir_all(&sw_dist)
        .unwrap_or_else(|e| panic!("failed to create sw dist dir {}: {e}", sw_dist.display()));

    let bashkit_wasm = workspace.join("target/wasm32-unknown-unknown/release/omni_bashkit.wasm");

    let should_rebuild_bashkit = !bashkit_wasm.exists()
        || file_newer_than(&bashkit_manifest, &bashkit_wasm)
        || tree_newer_than(&bashkit_src, &bashkit_wasm);

    if should_rebuild_bashkit {
        let cargo_status = Command::new("cargo")
            .args([
                "build",
                "-p",
                "omni-bashkit",
                "--target",
                "wasm32-unknown-unknown",
                "--release",
            ])
            .current_dir(workspace)
            .status()
            .unwrap_or_else(|e| panic!("failed to run cargo build for omni-bashkit: {e}"));
        assert!(
            cargo_status.success(),
            "cargo build failed for omni-bashkit"
        );
    }

    let out_js = sw_dist.join("omni-bashkit.js");
    let out_wasm = sw_dist.join("omni-bashkit_bg.wasm");
    let should_run_bindgen = !out_js.exists()
        || !out_wasm.exists()
        || file_newer_than(&bashkit_wasm, &out_js)
        || file_newer_than(&bashkit_wasm, &out_wasm);

    if should_run_bindgen {
        let bindgen = resolve_wasm_bindgen();
        let bindgen_status = Command::new(&bindgen)
            .args([
                "--target",
                "web",
                "--out-dir",
                sw_dist.to_str().unwrap(),
                "--out-name",
                "omni-bashkit",
                bashkit_wasm.to_str().unwrap(),
            ])
            .status()
            .unwrap_or_else(|e| panic!("failed to run wasm-bindgen at {}: {e}", bindgen.display()));
        assert!(
            bindgen_status.success(),
            "wasm-bindgen failed for omni-bashkit"
        );
    }
}

fn file_newer_than(source: &Path, target: &Path) -> bool {
    let src_meta = match fs::metadata(source) {
        Ok(meta) => meta,
        Err(_) => return false,
    };
    let dst_meta = match fs::metadata(target) {
        Ok(meta) => meta,
        Err(_) => return true,
    };

    let src_mtime = match src_meta.modified() {
        Ok(ts) => ts,
        Err(_) => return false,
    };
    let dst_mtime = match dst_meta.modified() {
        Ok(ts) => ts,
        Err(_) => return true,
    };

    src_mtime > dst_mtime
}

fn tree_newer_than(root: &Path, target: &Path) -> bool {
    if !root.exists() {
        return false;
    }
    if root.is_file() {
        return file_newer_than(root, target);
    }

    let entries = match fs::read_dir(root) {
        Ok(entries) => entries,
        Err(_) => return false,
    };

    for entry in entries.flatten() {
        let path = entry.path();
        if tree_newer_than(&path, target) {
            return true;
        }
    }

    false
}

fn resolve_wasm_bindgen() -> PathBuf {
    if let Some(home) = env::var_os("HOME") {
        let candidate =
            PathBuf::from(home).join(".local/share/.dx/tools/wasm-bindgen-0.2.114/wasm-bindgen");
        if candidate.exists() {
            return candidate;
        }
    }
    PathBuf::from("wasm-bindgen")
}

fn copy_if_stale(src: &Path, dst: &Path) -> std::io::Result<()> {
    if !src.exists() {
        return Ok(());
    }
    if dst.exists() && !file_newer_than(src, dst) {
        return Ok(());
    }
    if let Some(parent) = dst.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::copy(src, dst)?;
    Ok(())
}

fn normalize_zenfs_snippet_import(public_dir: &PathBuf) -> std::io::Result<()> {
    let bashkit_js = public_dir.join("omni-bashkit.js");
    if !bashkit_js.exists() {
        return Ok(());
    }

    let mut js = fs::read_to_string(&bashkit_js)?;
    let needle = "./snippets/omni-zenfs-";
    let Some(start) = js.find(needle) else {
        return Ok(());
    };

    let tail = &js[start + needle.len()..];
    let Some(end_rel) = tail.find("/omni-zenfs.js") else {
        return Ok(());
    };
    let hash = &tail[..end_rel];
    if hash.is_empty() {
        return Ok(());
    }

    let hashed_file = public_dir
        .join("snippets")
        .join(format!("omni-zenfs-{hash}"))
        .join("omni-zenfs.js");
    if !hashed_file.exists() {
        return Ok(());
    }

    let stable_dir = public_dir.join("snippets").join("omni-zenfs");
    fs::create_dir_all(&stable_dir)?;
    fs::copy(&hashed_file, stable_dir.join("omni-zenfs.js"))?;

    let old = format!("./snippets/omni-zenfs-{hash}/omni-zenfs.js");
    let new = "./snippets/omni-zenfs/omni-zenfs.js";
    js = js.replace(&old, new);
    fs::write(&bashkit_js, js)?;

    Ok(())
}

fn copy_dir_recursive_if_stale(src: &Path, dst: &Path) -> std::io::Result<()> {
    fs::create_dir_all(dst)?;
    for entry in fs::read_dir(src)? {
        let entry = entry?;
        let src_path = entry.path();
        let dst_path = dst.join(entry.file_name());
        if src_path.is_dir() {
            copy_dir_recursive_if_stale(&src_path, &dst_path)?;
        } else {
            copy_if_stale(&src_path, &dst_path)?;
        }
    }
    Ok(())
}
