versionConstraint: ">=2.0.0"
telemetry: false

projects:
  omni-ui: omni-ui
  omni-glue: omni-rt/crates/omni-glue
  omni-protocol: omni-rt/crates/omni-protocol
  omni-bashkit: omni-rt/crates/omni-bashkit
  omni-zenfs: omni-rt/crates/omni-zenfs
  omni-deepagents: omni-rt/crates/omni-deepagents
  omni-util: omni-rt/packages/omni-util
  omni-docxjs: omni-rt/packages/omni-docxjs
  omni-dicebear: omni-rt/packages/omni-dicebear
  omni-dock: omni-rt/packages/omni-dock
  omni-dockbar: omni-rt/packages/omni-dockbar
  omni-marked: omni-rt/packages/omni-marked
  omni-monaco: omni-rt/packages/omni-monaco
  omni-pdfjs: omni-rt/packages/omni-pdfjs
  omni-pptx-renderer: omni-rt/packages/omni-pptx-renderer
  omni-plyr: omni-rt/packages/omni-plyr
  omni-pretext: omni-rt/packages/omni-pretext
  omni-sheetjs: omni-rt/packages/omni-sheetjs
  omni-inference: omni-rt/packages/omni-inference
  omni-sw: omni-rt/packages/omni-sw
  omni-wc: omni-wc

vcs:
  provider: github
  defaultBranch: main

pipeline:
  installDependencies:
    - node
  logRunningCommand: true

hasher:
  ignorePatterns:
    - "**/dist/**/*"
    - "**/storybook-static/**/*"
    - "**/target/**/*"
    - "**/release/**/*"
    - "**/wasm-dev/**/*"
    - "**/node_modules/**/*"
    - "omni-ui/public/**/*"
  ignoreMissingPatterns:
    - "**/build.rs"
    - "**/build.ts"
    - "**/build.mjs"
    - "**/Cargo.toml"
    - "**/Dioxus.toml"
    - "**/clippy.toml"
    - "**/package.json"
    - "**/tsconfig.json"
    - "**/tsconfig.*.json"